[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "0x79b8ff"  # Light blue (similar to GitHub Dark's accents)
index = 16

[[colors.indexed_colors]]
color = "0xfa4549"  # Red (matches GitHub's error color)
index = 17

[colors.bright]
black = "0x2d333b"  # GitHub Dark background shade
blue = "0x539bf5"   # GitHub Dark blue
cyan = "0x56d4dd"   # GitHub Dark cyan
green = "0x6bc46d"  # GitHub Dark green
magenta = "0xdcbdfb"  # GitHub Dark magenta
red = "0xff7b72"    # GitHub Dark red
white = "0xd1d5da"  # GitHub Dark white
yellow = "0xe3b341"  # GitHub Dark yellow

[colors.normal]
black = "0x1b1f24"  # Darker background for normal text
blue = "0x539bf5"   # Same as bright blue for consistency
cyan = "0x56d4dd"   # Cyan similar to the GitHub theme
green = "0x6bc46d"  # Green matching GitHub Dark
magenta = "0xdcbdfb"  # GitHub Dark magenta
red = "0xff7b72"    # GitHub Dark red
white = "0xb1bac4"  # Slightly darker white for normal text
yellow = "0xe3b341"  # Yellow for warnings/accents

[colors.primary]
background = "0x0d1117"  # GitHub Dark main background color
foreground = "0xc9d1d9"  # GitHub Dark foreground (text)

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Beam"

[env]
TERM = "alacritty"

[font]
normal = {family = "MonoLisa Nerd Font Mono", style = "Regular"}
bold = {family = "MonoLisa Nerd Font Mono", style = "Bold"}
size = 12.0

# [font.glyph_offset]
# x = 0
# y = 0
#
# [font.offset]
# x = 0
# y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.90  # Slightly darker opacity for GitHub Dark feel
blur = true
decorations = "none"
startup_mode = "Windowed"

[window.dimensions]
columns = 110
lines = 52

[window.padding]
x = 4
y = 0
